# security:
#   oauth2:
#     resource:
#       userInfoUri: http://localhost:8901/auth/user
      
spring:
  security:
    oauth2:
      client:
        provider:
          my-oauth-provider:
            token-uri: http://localhost:8901/userinfo
      
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
