spring:
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://eb-discovery.herokuapp.com/eureka/
