spring:
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://eb-discovery.herokuapp.com/eureka/
