spring:
  boot:
    admin:
      client:
        url: http://localhost:8085
  zipkin:
    baseUrl: http://localhost:9411

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
