spring:
  data:
    mongodb:
      uri: mongodb://customer:customer@localhost:27019/dbCustomer
  sleuth:
    sampler:
      percentage: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081
