spring:
  data:
    mongodb:
      uri: mongodb://customer:customer@localhost:27019/dbCustomer
  boot:
    admin:
      client:
        url: http://localhost:8085

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user
      
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081
