spring:
  boot:
    admin:
      client:
        url: http://localhost:8085

eureka:
  server:
    eviction-interval-timer-in-ms: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8761
