spring:
  data:
    mongodb:
      uri: mongodb://evaluation:evaluation@localhost:27017/dbEvaluation
  boot:
    admin:
      client:
        url: "http://localhost:8080"

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8083
