spring:
  boot:
    admin:
      client:
        url: http://localhost:8085

# zuul:
#   sensitiveHeaders: Cookie,Set-Cookie

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555
  
security:
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: https:localhost:8901/auth/oauth/token
      userAuthorizationUri: https:localhost:8901/auth/oauth/authorize
