spring:
  boot:
    admin:
      client:
        url: http://localhost:8085

zuul:
  sensitiveHeaders: Cookie,Set-Cookie,Authorization

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555
