spring:
  boot:
    admin:
      client:
        url: http://localhost:8085

zuul:
  sensitiveHeaders: Cookie,Set-Cookie

security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: https://localhost/auth/oauth/token
      userAuthorizationUri: https://localhost/auth/oauth/authorize

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555
