spring:
  boot:
    admin:
      client:
        url: http://localhost:8085

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-services: *
  routes:
    eb:
      serviceId: eb-customer

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555
