spring:
  boot:
    admin:
      client:
        url: http://localhost:8085

zuul:
  sensitiveHeaders: Cookie,Set-Cookie

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

security:
  oauth2:
    client:
      client-id: evilbrewer
      client-secret: evilbrewer
      access-token-uri: https://localhost/auth/oauth/token
      user-authorization-uri: https://localhost/auth/oauth/authorize
      scope: webclient
