spring:
  sleuth:
    sampler:
      percentage: 1.0

zuul:
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  ignoredServices: 'eb-config-server, eb-discovery, eb-security, eb-admin, eb-zipkin-server'

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555
