spring:
  boot:
    admin:
      client:
        url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user

server:
  port: 5555
