spring:
  boot:
    admin:
      client:
        url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

endpoints:
  security:
    name: eb-security
    oauth-url: auth/oauth/token
