spring:
  boot:
    admin:
      client:
        url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  signing-key: ${spring.application.name}

server:
  port: 8901
  servlet:
    contextPath: /auth
