spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/db_security
    username: evilbrewer
    password: security
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8901
  servlet:
    contextPath: /auth
