spring:
  sleuth:
    sampler:
      percentage: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
  
orika:
  enabled: true
  useBuiltinConverters: true
  useAutoMapping: true
  mapNulls: true
  dumpStateOnException: true
  favorExtension: true
  captureFieldContext: true
