spring:
  data:
    mongodb:
      uri: mongodb://supplies:supplies@localhost:27018/dbSupplies
  sleuth:
    sampler:
      percentage: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082