spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_security
    username: ebsecurity
    password: ebsecurity
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  boot:
    admin:
      client:
        url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  signing-key: ${spring.application.name}

server:
  port: 8901
  servlet:
    contextPath: /auth
