spring:
  data:
    mongodb:
      uri: mongodb://users:users@localhost:27019/dbUsers
  sleuth:
    sampler:
      percentage: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081