spring:
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 6379
    expirationTime: 86400

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false

server:
  port: 8081

endpoints:
  countries:
    name: restCountries
    host: https://restcountries.eu/
    connectTimeout: 30000
    readTimeout: 30000
