spring:
  data:
    mongodb:
      uri: mongodb://status:status@localhost:27020/dbStatus
  boot:
    admin:
      client:
        url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8084
